include:
# - board: nice_nano@2.0.0
#   shield: settings_reset
# - board:  nrfmicro@1.1.0/nrf52840/flipped
#   shield: settings_reset
# - shield: cradio_left
#   board: nice_nano
# - shield: cradio_right
#   board: nice_nano

# Hillside 48 - Using generic_3x6 + extras
# - board: nice_nano/nrf52840
#   shield: hillside48_left
#   snippet: studio-rpc-usb-uart
# - board: nice_nano/nrf52840
#   shield: hillside48_right

# A_dux - Using generic_3x5 and zmk
# Om - uses this also
# - board: nice_nano/nrf52840
#   shield: a_dux_left
#   snippet: studio-rpc-usb-uart
#   cmake-args: -DCONFIG_ZMK_STUDIO=y
# - board: nice_nano/nrf52840
#   shield: a_dux_right

# A_dux - Using generic_3x5 and zmk
# Om - uses this also
# - board: nice_nano_v2
#   shield: a_dux_left
# - board: nice_nano_v2
#   shield: a_dux_right
# # HyperGarlic - Using generic_3x5 (no Studio support in shield)
# May not work wired
# - board: nice_nano/nrf52840
#   shield: hypergarlic_left
# - board: nice_nano/nrf52840
#   shield: hypergarlic_right

# # Kaz - Using generic_3x5 with custom shield (wired split)
- board: nice_nano/nrf52840
  shield: kaz_left
  snippet: studio-rpc-usb-uart
- board: nice_nano/nrf52840
  shield: kaz_right

# # Cradio
# # HyperGol(ic - Sold
# # Sweep
# # New board naming
# - board: nice_nano_v2
#   shield: cradio_left
#   # snippet: studio-rpc-usb-uart
#   # cmake-args: -DCONFIG_ZMK_STUDIO=y
# - board: nice_nano_v2
#   shield: cradio_right
# # Cradio36 - Using generic_3x6
# - board: nice_nano/nrf52840
#   shield: cradio36_left 
# - board: nice_nano/nrf52840
#   shield: cradio36_right

# # Cradios - Using generic_3x6 (no outer columns, no Studio support)
# - board: nice_nano/nrf52840
#   shield: cradios_left
# - board: nice_nano/nrf52840
#   shield: cradios_right

# HyperGolic - Bluetooth split keyboard 
# Does not work Q/B switched
# - board: nice_nano/nrf52840
#   shield: hypergolic_left
# - board: nice_nano/nrf52840
#   shield: hypergolic_right
