# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano/nrf52840
#     shield: reviung41
#
---
include:

# Generic 3x5 - for keymap-editor testing
# - board: nice_nano/nrf52840
#   shield: generic_3x5_left
#   snippet: studio-rpc-usb-uart
#   cmake-args: -DCONFIG_ZMK_STUDIO=y
# - board: nice_nano/nrf52840
#   shield: generic_3x5_right

# Generic 3x6 - for keymap-editor testing
# - board: nice_nano/nrf52840
#   shield: generic_3x6_left
#   snippet: studio-rpc-usb-uart
#   cmake-args: -DCONFIG_ZMK_STUDIO=y
# - board: nice_nano/nrf52840
#   shield: generic_3x6_right

# Hillside 48 - Using generic_3x6 + extras
- board: nrfmicro/nrf52840
  shield: hillside48_left
  snippet: studio-rpc-usb-uart
  cmake-args: -DCONFIG_ZMK_STUDIO=n
- board: nrfmicro/nrf52840
  shield: hillside48_right

  # Hillside 48
#   Comment out below if you do not have this board, to save build time
  # - board: nice_nano_v2
  #   shield: hillside48_left
  # - board: nice_nano_v2
  #   shield: hillside48_right

# A_dux - Using generic_3x5 and zmk
# Om - uses this also
# - board: nice_nano/nrf52840
#   shield: a_dux_left
#   snippet: studio-rpc-usb-uart
#   cmake-args: -DCONFIG_ZMK_STUDIO=y
# - board: nice_nano/nrf52840
#   shield: a_dux_right

# # HyperGarlic - Using generic_3x5 (no Studio support in shield)
# May not work wired
# - board: nice_nano/nrf52840
#   shield: hypergarlic_left
# - board: nice_nano/nrf52840
#   shield: hypergarlic_right

# # Kaz - Using generic_3x5 with custom shield (wired split)
# - board: nice_nano/nrf52840
#   shield: kaz_left
# - board: nice_nano/nrf52840
#   shield: kaz_right

# # Cradio
# # HyperGolic - Sold
# - board: nice_nano/nrf52840
#   shield: cradio_left
# - board: nice_nano/nrf52840
#   shield: cradio_right

# # Cradio36 - Using generic_3x6
# - board: nice_nano/nrf52840
#   shield: cradio36_left 
# - board: nice_nano/nrf52840
#   shield: cradio36_right

# # Cradios - Using generic_3x6 (no outer columns, no Studio support)
# - board: nice_nano/nrf52840
#   shield: cradios_left
# - board: nice_nano/nrf52840
#   shield: cradios_right

# HyperGolic - Bluetooth split keyboard 
# Does not work Q/B switched
  # - board: nice_nano/nrf52840
  #   shield: hypergolic_left
  # - board: nice_nano/nrf52840
  #   shield: hypergolic_right

# - board: nice_nano/nrf52840
#   shield: settings_reset
