# Copyright (c) 2021 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Studio is enabled via the snippet in build.yaml
# Keeping this disabled here to avoid conflicts with split BLE
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_STUDIO_LOCKING=n
